#!/usr/bin/env bash
#
# Snapshot all GitHub issues (open and closed) into docs/issues.md as a single markdown file.
# Requires the `gh` CLI (authenticated). Run from anywhere; output path is repo-relative.
#
# Usage: docs/dump-issues.sh   (or: make dump-issues)

set -euo pipefail

# Resolve the directory this script lives in, so output lands in docs/ regardless of cwd.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$SCRIPT_DIR/issues.md"

if ! command -v gh >/dev/null 2>&1; then
  echo "error: gh CLI not found. Install it and run 'gh auth login'." >&2
  exit 1
fi

# Render each issue (with its comments) as a markdown section. gh's built-in --jq (no external jq needed).
body="$(gh issue list --state all --limit 200 \
  --json number,title,state,labels,url,body,comments \
  --jq '
    sort_by(.number) | reverse | .[] |
    "## #\(.number) — \(.title)\n\n" +
    "- **State:** \(.state | ascii_downcase)\n" +
    "- **Labels:** \(if (.labels | length) > 0 then ([.labels[].name] | join(", ")) else "_none_" end)\n" +
    "- **Link:** \(.url)\n" +
    "- **Comments:** \(.comments | length)\n\n" +
    (if (.body // "" | gsub("\\s";"")) == "" then "_No description._" else (.body | rtrimstr("\n")) end) +
    "\n\n" +
    (if (.comments | length) > 0 then
      "### Comments\n\n" +
      ([.comments[] |
        "**\(.author.login // "unknown")**" +
        (if .createdAt then " (\(.createdAt))" else "" end) + ":\n\n" +
        ((.body // "_(empty)_" | rtrimstr("\n") | split("\n") | map("> " + .) | join("\n"))) +
        "\n"
      ] | join("\n")) + "\n"
    else "" end) +
    "---\n"
  ')"

count="$(gh issue list --state all --limit 200 --json number --jq 'length')"

{
  echo "# Issues"
  echo
  echo "_Generated by \`docs/dump-issues.sh\` — do not edit by hand. Run \`make dump-issues\` to refresh._"
  echo
  echo "Issue count: **$count**"
  echo
  echo "---"
  echo
  printf '%s\n' "$body"
} > "$OUT"

echo "wrote $OUT ($count issues)"
